services:
  netmon:
    build:
      context: .
    container_name: netmon
    restart: unless-stopped
    network_mode: "host"
    cap_drop:
      - ALL
    cap_add:
      - NET_ADMIN
      - NET_RAW
